const DummyData = [
  {
    title: "Learn English",
    description: "Read A Book",
    priority: "Medium",
    id: 1,
    board: "English",
    status: "In Progress",
  },
  {
    title: "Learn Math",
    description: "Algebra",
    priority: "Low",
    id: 2,
    board: "Math",
    status: "ToDo",
  },
  {
    title: "Learn JS",
    description: "Functions",
    priority: "High",
    id: 3,
    board: "JS",
    status: "In Progress",
  },
  {
    title: "Learn English",
    description: "Alphabet",
    priority: "Medium",
    id: 4,
    board: "English",
    status: "Done",
  },
  {
    title: "Learn Math",
    description: "Using a calculator",
    priority: "Low",
    id: 5,
    board: "Math",
    status: "ToDo",
  },
  {
    title: "Learn JS",
    description: "Loops",
    priority: "High",
    id: 6,
    board: "JS",
    status: "Done",
  },
  {
    title: "Learn English",
    description: "Pronunciation",
    priority: "Medium",
    id: 7,
    board: "English",
    status: "In Progress",
  },
  {
    title: "Learn Math",
    description: "Count to 5",
    priority: "Low",
    id: 8,
    board: "Math",
    status: "ToDo",
  },
  {
    title: "Learn JS",
    description: "Objects",
    priority: "High",
    id: 9,
    board: "JS",
    status: "In Progress",
  },
  {
    title: "Learn English",
    description: "Song lyrics",
    priority: "Medium",
    id: 10,
    board: "English",
    status: "Done",
  },
  {
    title: "Learn Math",
    description: "Math is awesome",
    priority: "Low",
    id: 11,
    board: "Math",
    status: "ToDo",
  },
  {
    title: "Learn JS",
    description: "Project",
    priority: "High",
    id: 12,
    board: "JS",
    status: "Done",
  },
];

export default DummyData;
